### ISSUE TITLE
Feature Request: Change other player's glamour

### ISSUE THREAD

**Issue by inu-goro** [SheepGoMeh/VisibilityPlugin#63]
Hello, thank you for such a wonderful plugin.

When enjoying a main story dungeons or raids, those animal suit glamours are quite disturbing, and the enormous gleaming weapons assassinate my eyes.
I understand making players invisible in dungeons may cause trouble, so it possible to instead change the glamours of other players to something simple, like artifact armor or default race outfit?

**Comment by SheepGoMeh** [comment]
This falls under the same issue as making players invisible in dungeons, and is outside the scope of this plugin.

**Comment by Xelfen** [comment]
@inu-goro With Textools (and Penumbra also now), you can copy one equipment to another, so for example copy the emperor's hat for all the ridiculous animal helmets

For vfx (particle effects), it's more time-consuming, because you have to remove the vfx you don't want on every weapon (and armor now too unfortunately), it seems to me that there are mods and I wouldn't be surprised that people have done it privately and can share it.

for equipment that have a glow style, it is often possible to apply their variant on them to remove it
