### ISSUE TITLE
Voided players not currently being hidden?

### ISSUE THREAD

**Issue by t-l13** [SheepGoMeh/VisibilityPlugin#72]
Running 1.1.7.1, it doesn't appear the voidlist is working. If I target a player and use /voidtarget, I receive a chat message and it shows them added to the list in the chat, but they aren't hidden. They're actually in the void list, and the voidlist is enabled, but no results.

The "Hide all" buttons appear to work just fine. Voidlist does not, however. Tried clearing, reinstalling, relogging, etc. Nothing.

**Comment by SheepGoMeh** [comment]
Please switch to using the vanilla blacklist feature.
VoidList is getting sunset.

**Comment by drejjmit** [comment]
> Please switch to using the vanilla blacklist feature. VoidList is getting sunset.

Hide Pets, Minions, Chocobos and All players aren't an option in vanilla blacklist feature. Please don't abandon this project 🙏

**Comment by SheepGoMeh** [comment]
> > Please switch to using the vanilla blacklist feature. VoidList is getting sunset.
> 
> Hide Pets, Minions, Chocobos and All players aren't an option in vanilla blacklist feature. Please don't abandon this project 🙏

Only the voidlist feature (better blacklist before 7.0) is getting deprecated.
The rest of the features will stay and be improved upon.

**Comment by Zarixx-inc** [comment]
Extremely stupid decision to remove VoidList. Yes, the game's Blacklist does what VoidList does now, but Square shot themselves in the foot by not upping the 200 person cap to a much higher number which should have happened a long time ago.

Some of us that are stuck on bad servers have hit that 200/200 limit for a long time now, and my VoidList currently has almost 400 players on it from across Aether or ranging from dumb stuff they say in chat, to toxic players and stalkers that I often see visiting Siren (during EA when all plugins were down.) I can't even clean up the regular Blacklist because most of those players still currently play.

So you mean to tell me you're just going to drop it and tell every one that uses VoidList for legitimate reasons to "suck it up and deal with those that traumatize you." This is bullshit.

**Comment by Vhailor19** [comment]
> Extremely stupid decision to remove VoidList. Yes, the game's Blacklist does what VoidList does now, but Square shot themselves in the foot by not upping the 200 person cap to a much higher number which should have happened a long time ago so the feature is DoA.
> 
> Some of us that are stuck on bad servers have hit that 200/200 limit for a long time now, and my VoidList currently has almost 400 players on it from across Aether or ranging from dumb stuff they say in chat, to toxic players and stalkers that I often see visiting Siren (during EA when all plugins were down.) I can't even clean up the regular Blacklist because most of those players still currently play.
> 
> So you mean to tell me you're just going to drop it and tell every one that uses VoidList for legitimate reasons to "suck it up" and deal with all the people we've had traumatize us? This is bullshit.

Holy crap dude.  Rude.  This is literally free software, made for us by people who want to improve the game, and you're cursing them out over a decision you disagree with?  Good lord.  I had to make an account just to call you out for this; absolutely disgusting entitlement.

That said, I do share your disappointment over the deprecation of this feature, and I hope that the decision is reconsidered for future versions.  Due to the 200-character limit, SE's blacklist simply isn't a replacement for what Voidlist allowed me to do.  Which is fine.  I'll learn to live without it, being far more selective with who I add.  But I would be extremely grateful if it made a return one day.

**Comment by PrincessRTFM** [comment]
> Extremely stupid decision to remove VoidList. Yes, the game's Blacklist does what VoidList does now, but Square shot themselves in the foot by not upping the 200 person cap to a much higher number which should have happened a long time ago so the feature is DoA.
> 
> Some of us that are stuck on bad servers have hit that 200/200 limit for a long time now, and my VoidList currently has almost 400 players on it from across Aether or ranging from dumb stuff they say in chat, to toxic players and stalkers that I often see visiting Siren (during EA when all plugins were down.) I can't even clean up the regular Blacklist because most of those players still currently play.
> 
> So you mean to tell me you're just going to drop it and tell every one that uses VoidList for legitimate reasons to "suck it up" and deal with all the people we've had traumatize us? This is bullshit.

How _not_ to get a dev to reconsider: exhibit A.

Either hide all other players except your friends and FC, or curate your blocks. If you block people for just saying stupid shit in chat, you're gonna be blocking a lot of people, and that's on _you_ to handle.

> That said, I do share your disappointment over the deprecation of this feature, and I hope that the decision is reconsidered for future versions. Due to the 200-character limit, SE's blacklist simply isn't a replacement for what Voidlist allowed me to do. Which is fine. I'll learn to live without it, being far more selective with who I add. But I would be extremely grateful if it made a return one day.

Unfortunately, this is not likely. _Extremely_ not likely. I'm one of Sheep's co-developers, so I can speak with some certainty on the subject.

The feature was complex and difficult to do well, because _every single frame_, every user in the area needed to be checked _by name_ (and string comparisons are, at this level, surprisingly expensive) against _every_ name on the list. I know for a fact that Sheep did a _lot_ of work optimising to avoid absolutely tanking framerates, because they talked to me about it while working on it. On top of that, a lot of users consistently complained, or found problems with it that required significant effort to fix, or just added so many users to their lists that their FPS died and then blamed Sheep for it.

Frankly, neither of us wants to ever touch something like this again, partially because it was just awful trying to make it viable, and partially because a chunk of users were such assholes that they ruined things for everyone else.

**Comment by Vhailor19** [comment]
> Unfortunately, this is not likely. _Extremely_ not likely. I'm one of Sheep's co-developers, so I can speak with some certainty on the subject.
> 
> The feature was complex and difficult to do well, because _every single frame_, every user in the area needed to be checked _by name_ (and string comparisons are, at this level, surprisingly expensive) against _every_ name on the list. I know for a fact that Sheep did a _lot_ of work optimising to avoid absolutely tanking framerates, because they talked to me about it while working on it. On top of that, a lot of users consistently complained, or found problems with it that required significant effort to fix, or just added so many users to their lists that their FPS died and then blamed Sheep for it.
> 
> Frankly, neither of us wants to ever touch something like this again, partially because it was just awful trying to make it viable, and partially because a chunk of users were such assholes that they ruined things for everyone else.

Thank you for the detail, PrincessRTFM!  I had absolutely no idea it was so tricky to make work right; I am extra appreciative now for all the years of use I got out of the functionality. I'll readily admit I was using it for non-standard and petty reasons - mostly hiding people with overly goofy Glamours or who spammed particularly annoying emotes or abilities in town. 

Keep at it, and do your best to ignore people like Zarixx.  There are countless users like me who have had their experiences greatly impacted through efforts like yours and Sheep's.  Thanks again for the detail!

**Comment by Zarixx-inc** [comment]
Lmao whatever. Literally very valid points to keep this feature in for people and you idiots want to just gang up on people instead. This is why WoW addon makers keep things like Personal Blacklist in play even after their ignore system got changed around, because people understand it's valuable to block out the trolls or for M+/Raiding, actually keep track of the awful players to remove them/leave.

But this is FFXIV. You all want to take Ls all the time and the responses towards me is a clear-cut example of why LGBT Faggot Culture continues to ruin games.

**Comment by SheepGoMeh** [comment]
Thank you to @PrincessRTFM for explaining things in such a clear way :)
This issue has been completely derailed and will thus be locked.
