### ISSUE TITLE
[Issue] Load Error

### ISSUE THREAD

**Issue by AzheNorth** [SheepGoMeh/VisibilityPlugin#92]
Hey and first off thanks for the tool in general.

Last night, and again this morning, Visibility has apparently failed to load, adding '(load error)' in its title.
With the additional message, 'This plugin has failed to load. Please contact the author for more information,' here I am.
Uncertain what might cause this, so I'll simply bring attention to it and hope for the best.

Keep up the good work.

**Comment by SheepGoMeh** [comment]
The error itself is far too vague, and it is entirely dependant on your setup.
I recommend that you contact Dalamud support via their Discord and provide the appropriate logs.

**Comment by Ganonderp** [comment]
May as well ask here since it's relevant (and i've had this issue for several days now too.)

Before doing "Reset plugin data and reload" to see if that fixes the issue, is there a file saved somewhere I can keep and re-import that has my entire list for Whitelist/Voidlist so I don't lose all those?

**Comment by SheepGoMeh** [comment]
They're saved in your Visibility config file, located at `%APPDATA%\XIVLauncher\pluginConfigs\Visibility.json`
